[package]
name = "zcl"
version = "0.1.0"
edition = "2024"

[dependencies]
crabtime = "1.1.3"
paste = "1.0.15"
thiserror = { version = "2.0.12", default-features = false }

[features]
default = ["std"]
std = []
